### ISSUE TITLE
安装失败

### ISSUE THREAD

**Issue by blockChainB** [rainyx/rxmemscan#1]
main.cpp:11:10: fatal error: 'readline/readline.h' file not found
#include <readline/readline.h>
         ^
1 error generated.
make[3]: *** [/Users/fei/Downloads/rxmems/.theos/obj/debug/arm64/main.cpp.471f0381.o] Error 1
make[2]: *** [/Users/fei/Downloads/rxmems/.theos/obj/debug/arm64/rxmemscan] Error 2
make[1]: *** [internal-tool-all_] Error 2
make: *** [rxmemscan.all.tool.variables] Error 2

挺好奇的呀..
谢谢..

**Comment by rainyx** [comment]
readline 在我另一个repo里面有编译好的a（地址：https://github.com/rainyx/libreadline-arm ），当然你也可以自己编译。然后将编译好的a和headers分别放入$THEOS/vendor/lib 和 $THEOS/vendor/header中，重新编译rxmemscan即可。

**Comment by jmpews** [comment]
@rainyx 最近也在搞一个 interactive cli , 发现 readline 太复杂需要目标机子已经安装了readline, 倒是有个 linenoise 很简洁 但是不能编译成 arm. 😂

**Comment by rainyx** [comment]
@jmpews 可以编译，改下Makefile。
`CC = xcrun --sdk iphoneos clang -arch armv7 -arch arm64 -miphoneos-version-min=6.0`

> otool -hv linenoise_example
Mach header
      magic cputype cpusubtype  caps    filetype ncmds sizeofcmds      flags
   MH_MAGIC     ARM         V7  0x00     EXECUTE    16       1200   NOUNDEFS DYLDLINK TWOLEVEL PIE
Mach header
      magic cputype cpusubtype  caps    filetype ncmds sizeofcmds      flags
MH_MAGIC_64   ARM64        ALL  0x00     EXECUTE    16       1464   NOUNDEFS DYLDLINK TWOLEVEL PIE

**Comment by jmpews** [comment]
@rainyx 最后我还是用了readline 😁

https://github.com/jmpews/rtspy/blob/master/MachoRuntimeSpy/Makefile

**Comment by liumazi** [comment]
这个readline是要自己编译的是吗
还以为在mac上brew install readline就好了呢
另外手机上还要brew install readline才可以是吗 ？

**Comment by liumazi** [comment]
> readline 在我另一个repo里面有编译好的a（地址：https://github.com/rainyx/libreadline-arm ），当然你也可以自己编译。然后将编译好的a和headers分别放入$THEOS/vendor/lib 和 $THEOS/vendor/header中，重新编译rxmemscan即可。

应该是放在$THEOS/vendor/include
